# Generated by Django 3.1.7 on 2021-03-01 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Category Name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter course name', max_length=200)),
                ('credit', models.IntegerField(help_text='Enter credit score')),
                ('duration', models.IntegerField(help_text='Enter course duration')),
                ('category', models.ForeignKey(help_text='Enter Category', on_delete=django.db.models.deletion.CASCADE, to='restapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_seats', models.IntegerField(help_text='Enter total seats')),
                ('rem_seats', models.IntegerField(help_text='Enter remaining seats')),
                ('start_date', models.DateField(help_text='Enter course start date')),
                ('end_date', models.DateField(help_text='Enter course end date')),
                ('course', models.ForeignKey(help_text='Enter Course ', on_delete=django.db.models.deletion.CASCADE, to='restapp.course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=70)),
                ('dob', models.DateField(help_text='Enter you DOB')),
                ('phone', models.IntegerField(blank=True)),
                ('email', models.EmailField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('pin', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=70)),
                ('dob', models.DateField(help_text='Enter you DOB')),
                ('phone', models.IntegerField(blank=True)),
                ('email', models.EmailField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('pin', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolled_Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(help_text='Enter Course Session ', on_delete=django.db.models.deletion.CASCADE, to='restapp.course_session')),
                ('enrolled_by', models.ForeignKey(help_text='Enter User ', on_delete=django.db.models.deletion.CASCADE, to='restapp.student')),
            ],
        ),
        migrations.AddField(
            model_name='course_session',
            name='taken_by',
            field=models.ForeignKey(help_text='Enter Faculty', null=True, on_delete=django.db.models.deletion.CASCADE, to='restapp.faculty'),
        ),
    ]
