# Generated by Django 3.1.7 on 2021-03-01 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_auto_20210301_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.IntegerField(help_text='Enter credit score', validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(10)]),
        ),
    ]
