# Generated by Django 3.1.7 on 2021-03-01 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0005_auto_20210301_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(help_text='Enter course duration', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course_session',
            name='rem_seats',
            field=models.IntegerField(help_text='Enter remaining seats', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course_session',
            name='tot_seats',
            field=models.IntegerField(help_text='Enter total seats', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='pin',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(6)]),
        ),
    ]
