# Generated by Django 3.1.7 on 2021-03-01 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0008_auto_20210302_0247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['category']},
        ),
        migrations.AlterModelOptions(
            name='course_session',
            options={'ordering': ['start_date', 'course', 'taken_by']},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['id']},
        ),
    ]
