# Generated by Django 3.1.7 on 2021-03-01 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0009_auto_20210302_0250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course_session',
            options={'ordering': ['course__category', 'start_date', 'course', 'taken_by']},
        ),
    ]
