# Generated by Django 3.1.7 on 2021-03-01 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0012_auto_20210302_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
    ]
