# Generated by Django 3.1.7 on 2021-03-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0013_auto_20210302_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='dob',
            field=models.DateField(blank=True, help_text='Enter you DOB', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, help_text='Enter you DOB', null=True),
        ),
    ]
