# Generated by Django 3.1.7 on 2021-03-02 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0014_auto_20210302_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_session',
            name='end_date',
            field=models.DateField(help_text='Enter course end date', null=True),
        ),
        migrations.AlterField(
            model_name='course_session',
            name='rem_seats',
            field=models.IntegerField(help_text='Enter remaining seats', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course_session',
            name='start_date',
            field=models.DateField(help_text='Enter course start date', null=True),
        ),
        migrations.AlterField(
            model_name='course_session',
            name='tot_seats',
            field=models.IntegerField(help_text='Enter total seats', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
