# Generated by Django 3.1.7 on 2021-03-02 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0015_auto_20210302_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_session',
            name='course',
            field=models.ForeignKey(help_text='Enter Course ', null=True, on_delete=django.db.models.deletion.CASCADE, to='restapp.course'),
        ),
    ]
