# Generated by Django 3.1.7 on 2021-03-07 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0020_module_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled_session',
            name='enrolled_by',
            field=models.ForeignKey(help_text='Enter User ', on_delete=django.db.models.deletion.CASCADE, related_name='enrolled', to='restapp.student'),
        ),
    ]
