# Generated by Django 3.1.7 on 2021-03-10 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0021_auto_20210307_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(help_text='Enter Course ', null=True, on_delete=django.db.models.deletion.CASCADE, to='restapp.course'),
        ),
        migrations.AlterField(
            model_name='module',
            name='desc',
            field=models.TextField(help_text='Enter moudule description', null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(help_text='Enter moudule name', max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='topics',
            field=models.ManyToManyField(help_text='Enter Topic ', null=True, to='restapp.Topic'),
        ),
    ]
