# Generated by Django 3.1.7 on 2021-03-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0023_auto_20210311_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.ManyToManyField(help_text='Enter Modules ', null=True, to='restapp.Module'),
        ),
    ]
